/** GET MULTIPLE MOVIE */
export const GET_TRENDINGS = 'GET_TRENDINGS';
export const GET_POPULAR = 'GET_POPULAR';
export const GET_SIMILAR = 'GET_SIMILAR';
export const GET_NOWPLAYING = 'GET_NOWPLAYING';
export const GET_TOPRATED = 'GET_TOPRATED';
export const GET_UPCOMING = 'GET_UPCOMING';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';

/** SINGLE MOVIE ACTION TYPES */
export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_ACTORS = 'GET_MOVIE_ACTIONS';

